// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxatRWmOcmX9yrajSlzbHGIgzRtHSSOU0',
    appId: '1:52717791660:web:65bcec4ed833e218377209',
    messagingSenderId: '52717791660',
    projectId: 'brewcrew-8f4d9',
    authDomain: 'brewcrew-8f4d9.firebaseapp.com',
    storageBucket: 'brewcrew-8f4d9.appspot.com',
    measurementId: 'G-S8NZ7ZRJE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuK2qjtyUmkRf-dGWRGDbc1ldt_Puw43I',
    appId: '1:52717791660:android:cad984d12b2e93f2377209',
    messagingSenderId: '52717791660',
    projectId: 'brewcrew-8f4d9',
    storageBucket: 'brewcrew-8f4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVF2hHAqt7GlX-_0O2_ahdzr8yQVacO4s',
    appId: '1:52717791660:ios:0c826373b0a218a3377209',
    messagingSenderId: '52717791660',
    projectId: 'brewcrew-8f4d9',
    storageBucket: 'brewcrew-8f4d9.appspot.com',
    iosClientId: '52717791660-8gevjugm93odqtd5ocgcmtb6urtlj551.apps.googleusercontent.com',
    iosBundleId: 'com.asavathiratham.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVF2hHAqt7GlX-_0O2_ahdzr8yQVacO4s',
    appId: '1:52717791660:ios:0c826373b0a218a3377209',
    messagingSenderId: '52717791660',
    projectId: 'brewcrew-8f4d9',
    storageBucket: 'brewcrew-8f4d9.appspot.com',
    iosClientId: '52717791660-8gevjugm93odqtd5ocgcmtb6urtlj551.apps.googleusercontent.com',
    iosBundleId: 'com.asavathiratham.brewCrew',
  );
}
